<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.ce.ebiz.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://ws.ce.ebiz.com/" name="EBizGenericInvokerImplService" targetNamespace="http://service.ce.ebiz.com/">
    <wsdl:import location="definitions.wsdl" namespace="http://ws.ce.ebiz.com/"></wsdl:import>
    <wsdl:binding name="EBizGenericInvokerImplServiceSoapBinding" type="ns1:EBizGenericInvoker">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="invoke">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="invoke">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="invokeResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="EBizGenericInvokerImplService">
        <wsdl:port binding="tns:EBizGenericInvokerImplServiceSoapBinding" name="EBizGenericInvokerImplPort">
            <soap:address location="http://test3.alignetsac.com/sfewsperu1/ws/invoker"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>