-- use einvoice;

-- drop table SPE_CANCELDETAIL;
-- drop table SPE_CANCELHEADER;
-- drop table SPE_EINVOICEDETAIL;
-- drop table SPE_EINVOICEHEADER;
-- drop table SPE_SUMMARYDETAIL;
-- drop table SPE_SUMMARYHEADER;

create table SPE_CANCELDETAIL (
    numeroDocumentoEmisor varchar(20) not null,
    numeroFila varchar(5) not null,
    resumenId varchar(17) not null,
    tipoDocumentoEmisor varchar(1) not null,
    motivoBaja varchar(200) null,
    numeroDocumentoBaja varchar(8) not null,
    serieDocumentoBaja varchar(4) not null,
    tipoDocumento varchar(2) not null,
    primary key (numeroDocumentoEmisor, numeroFila, resumenId, tipoDocumentoEmisor)
)
lock datarows;

create table SPE_CANCELHEADER (
    numeroDocumentoEmisor varchar(20) not null,
    resumenId varchar(17) not null,
    tipoDocumentoEmisor varchar(1) not null,
    bl_cdr image null,
    bl_estadoProceso varchar(40) null,
    bl_estadoRegistro varchar(40) null,
    bl_firma varchar(4000) null,
    bl_hashFirma varchar(4000) null,
    bl_mensaje varchar(4000) null,
    bl_mensajeSunat varchar(4000) null,
    bl_pdf image null,
    bl_urlcdr varchar(4000) null,
    bl_urlpdf varchar(4000) null,
    bl_urlxmlubl varchar(4000) null,
    bl_xml image null,
    bl_xmlubl image null,
    correoEmisor varchar(100) not null,
    fechaEmisionComprobante varchar(10) not null,
    fechaGeneracionResumen varchar(10) not null,
    inHabilitado varchar(1) not null,
    razonSocialEmisor varchar(100) not null,
    resumenTipo varchar(2) not null,
    primary key (numeroDocumentoEmisor, resumenId, tipoDocumentoEmisor)
)
lock datarows;

create table SPE_EINVOICEDETAIL (
    numeroDocumentoEmisor varchar(20) not null,
    numeroOrdenItem varchar(4) not null,
    serieNumero varchar(13) not null,
    tipoDocumento varchar(2) not null,
    tipoDocumentoEmisor varchar(1) not null,
    cantidad varchar(25) not null,
    codigoAuxiliar100_1 varchar(4) null,
    codigoAuxiliar100_10 varchar(4) null,
    codigoAuxiliar100_2 varchar(4) null,
    codigoAuxiliar100_3 varchar(4) null,
    codigoAuxiliar100_4 varchar(4) null,
    codigoAuxiliar100_5 varchar(4) null,
    codigoAuxiliar100_6 varchar(4) null,
    codigoAuxiliar100_7 varchar(4) null,
    codigoAuxiliar100_8 varchar(4) null,
    codigoAuxiliar100_9 varchar(4) null,
    codigoAuxiliar250_1 varchar(4) null,
    codigoAuxiliar250_10 varchar(4) null,
    codigoAuxiliar250_2 varchar(4) null,
    codigoAuxiliar250_3 varchar(4) null,
    codigoAuxiliar250_4 varchar(4) null,
    codigoAuxiliar250_5 varchar(4) null,
    codigoAuxiliar250_6 varchar(4) null,
    codigoAuxiliar250_7 varchar(4) null,
    codigoAuxiliar250_8 varchar(4) null,
    codigoAuxiliar250_9 varchar(4) null,
    codigoAuxiliar40_1 varchar(4) null,
    codigoAuxiliar40_10 varchar(4) null,
    codigoAuxiliar40_2 varchar(4) null,
    codigoAuxiliar40_3 varchar(4) null,
    codigoAuxiliar40_4 varchar(4) null,
    codigoAuxiliar40_5 varchar(4) null,
    codigoAuxiliar40_6 varchar(4) null,
    codigoAuxiliar40_7 varchar(4) null,
    codigoAuxiliar40_8 varchar(4) null,
    codigoAuxiliar40_9 varchar(4) null,
    codigoAuxiliar500_1 varchar(4) null,
    codigoAuxiliar500_2 varchar(4) null,
    codigoAuxiliar500_3 varchar(4) null,
    codigoAuxiliar500_4 varchar(4) null,
    codigoAuxiliar500_5 varchar(4) null,
    codigoImporteReferencial varchar(2) null,
    codigoImporteUnitarioConImpues varchar(2) not null,
    codigoProducto varchar(30) null,
    codigoRazonExoneracion varchar(2) null,
    descripcion varchar(1700) not null,
    importeCargo varchar(15) null,
    importeDescuento varchar(15) null,
    importeIgv varchar(15) null,
    importeIsc varchar(15) null,
    importeReferencial varchar(15) null,
    importeTotalSinImpuesto varchar(15) not null,
    importeUnitarioConImpuesto varchar(35) not null,
    importeUnitarioSinImpuesto varchar(23) not null,
    textoAuxiliar100_1 varchar(100) null,
    textoAuxiliar100_10 varchar(100) null,
    textoAuxiliar100_2 varchar(100) null,
    textoAuxiliar100_3 varchar(100) null,
    textoAuxiliar100_4 varchar(100) null,
    textoAuxiliar100_5 varchar(100) null,
    textoAuxiliar100_6 varchar(100) null,
    textoAuxiliar100_7 varchar(100) null,
    textoAuxiliar100_8 varchar(100) null,
    textoAuxiliar100_9 varchar(100) null,
    textoAuxiliar250_1 varchar(250) null,
    textoAuxiliar250_10 varchar(250) null,
    textoAuxiliar250_2 varchar(250) null,
    textoAuxiliar250_3 varchar(250) null,
    textoAuxiliar250_4 varchar(250) null,
    textoAuxiliar250_5 varchar(250) null,
    textoAuxiliar250_6 varchar(250) null,
    textoAuxiliar250_7 varchar(250) null,
    textoAuxiliar250_8 varchar(250) null,
    textoAuxiliar250_9 varchar(250) null,
    textoAuxiliar40_1 varchar(40) null,
    textoAuxiliar40_10 varchar(40) null,
    textoAuxiliar40_2 varchar(40) null,
    textoAuxiliar40_3 varchar(40) null,
    textoAuxiliar40_4 varchar(40) null,
    textoAuxiliar40_5 varchar(40) null,
    textoAuxiliar40_6 varchar(40) null,
    textoAuxiliar40_7 varchar(40) null,
    textoAuxiliar40_8 varchar(40) null,
    textoAuxiliar40_9 varchar(40) null,
    textoAuxiliar500_1 varchar(250) null,
    textoAuxiliar500_2 varchar(250) null,
    textoAuxiliar500_3 varchar(250) null,
    textoAuxiliar500_4 varchar(250) null,
    textoAuxiliar500_5 varchar(250) null,
    tipoSistemaImpuestoISC varchar(2) null,
    unidadMedida varchar(3) not null,
    primary key (numeroDocumentoEmisor, numeroOrdenItem, serieNumero, tipoDocumento, tipoDocumentoEmisor)
)
lock datarows;

create table SPE_EINVOICEHEADER (
    numeroDocumentoEmisor varchar(20) not null,
    serieNumero varchar(13) not null,
    tipoDocumento varchar(2) not null,
    tipoDocumentoEmisor varchar(1) not null,
    baseImponiblePercepcion varchar(15) null,
    bl_cdr image null,
    bl_estadoProceso varchar(40) null,
    bl_estadoRegistro varchar(40) null,
    bl_firma varchar(4000) null,
    bl_hashFirma varchar(4000) null,
    bl_mensaje varchar(4000) null,
    bl_mensajeSunat varchar(4000) null,
    bl_pdf image null,
    bl_urlcdr varchar(4000) null,
    bl_urlpdf varchar(4000) null,
    bl_urlxmlubl varchar(4000) null,
    bl_xml image null,
    bl_xmlubl image null,
    codigoAuxiliar100_1 varchar(4) null,
    codigoAuxiliar100_10 varchar(4) null,
    codigoAuxiliar100_2 varchar(4) null,
    codigoAuxiliar100_3 varchar(4) null,
    codigoAuxiliar100_4 varchar(4) null,
    codigoAuxiliar100_5 varchar(4) null,
    codigoAuxiliar100_6 varchar(4) null,
    codigoAuxiliar100_7 varchar(4) null,
    codigoAuxiliar100_8 varchar(4) null,
    codigoAuxiliar100_9 varchar(4) null,
    codigoAuxiliar250_1 varchar(4) null,
    codigoAuxiliar250_10 varchar(4) null,
    codigoAuxiliar250_11 varchar(4) null,
    codigoAuxiliar250_12 varchar(4) null,
    codigoAuxiliar250_13 varchar(4) null,
    codigoAuxiliar250_14 varchar(4) null,
    codigoAuxiliar250_15 varchar(4) null,
    codigoAuxiliar250_16 varchar(4) null,
    codigoAuxiliar250_17 varchar(4) null,
    codigoAuxiliar250_18 varchar(4) null,
    codigoAuxiliar250_19 varchar(4) null,
    codigoAuxiliar250_2 varchar(4) null,
    codigoAuxiliar250_20 varchar(4) null,
    codigoAuxiliar250_21 varchar(4) null,
    codigoAuxiliar250_22 varchar(4) null,
    codigoAuxiliar250_23 varchar(4) null,
    codigoAuxiliar250_24 varchar(4) null,
    codigoAuxiliar250_25 varchar(4) null,
    codigoAuxiliar250_3 varchar(4) null,
    codigoAuxiliar250_4 varchar(4) null,
    codigoAuxiliar250_5 varchar(4) null,
    codigoAuxiliar250_6 varchar(4) null,
    codigoAuxiliar250_7 varchar(4) null,
    codigoAuxiliar250_8 varchar(4) null,
    codigoAuxiliar250_9 varchar(4) null,
    codigoAuxiliar40_1 varchar(4) null,
    codigoAuxiliar40_10 varchar(4) null,
    codigoAuxiliar40_11 varchar(4) null,
    codigoAuxiliar40_12 varchar(4) null,
    codigoAuxiliar40_13 varchar(4) null,
    codigoAuxiliar40_14 varchar(4) null,
    codigoAuxiliar40_15 varchar(4) null,
    codigoAuxiliar40_16 varchar(4) null,
    codigoAuxiliar40_17 varchar(4) null,
    codigoAuxiliar40_18 varchar(4) null,
    codigoAuxiliar40_19 varchar(4) null,
    codigoAuxiliar40_2 varchar(4) null,
    codigoAuxiliar40_20 varchar(4) null,
    codigoAuxiliar40_3 varchar(4) null,
    codigoAuxiliar40_4 varchar(4) null,
    codigoAuxiliar40_5 varchar(4) null,
    codigoAuxiliar40_6 varchar(4) null,
    codigoAuxiliar40_7 varchar(4) null,
    codigoAuxiliar40_8 varchar(4) null,
    codigoAuxiliar40_9 varchar(4) null,
    codigoAuxiliar500_1 varchar(4) null,
    codigoAuxiliar500_2 varchar(4) null,
    codigoAuxiliar500_3 varchar(4) null,
    codigoAuxiliar500_4 varchar(4) null,
    codigoAuxiliar500_5 varchar(4) null,
    codigoLeyenda_1 varchar(4) null,
    codigoLeyenda_10 varchar(4) null,
    codigoLeyenda_11 varchar(4) null,
    codigoLeyenda_12 varchar(4) null,
    codigoLeyenda_13 varchar(4) null,
    codigoLeyenda_14 varchar(4) null,
    codigoLeyenda_15 varchar(4) null,
    codigoLeyenda_16 varchar(4) null,
    codigoLeyenda_17 varchar(4) null,
    codigoLeyenda_18 varchar(4) null,
    codigoLeyenda_19 varchar(4) null,
    codigoLeyenda_2 varchar(4) null,
    codigoLeyenda_20 varchar(4) null,
    codigoLeyenda_3 varchar(4) null,
    codigoLeyenda_4 varchar(4) null,
    codigoLeyenda_5 varchar(4) null,
    codigoLeyenda_6 varchar(4) null,
    codigoLeyenda_7 varchar(4) null,
    codigoLeyenda_8 varchar(4) null,
    codigoLeyenda_9 varchar(4) null,
    codigoSerieNumeroAfectado varchar(2) null,
    correoAdquiriente varchar(100) not null,
    correoEmisor varchar(100) not null,
    departamentoEmisor varchar(30) null,
    departamentoPtoLlegada varchar(30) null,
    departamentoPtoPartida varchar(30) null,
    descripcionDetraccion varchar(100) null,
    descuentosGlobales varchar(15) null,
    direccionCompletaPtoLlegada varchar(100) null,
    direccionCompletaPtoPartida varchar(100) null,
    direccionEmisor varchar(100) null,
    distritoEmisor varchar(30) null,
    distritoPtoLlegada varchar(30) null,
    distritoPtoPartida varchar(30) null,
    fechaEmision varchar(10) not null,
    inHabilitado varchar(1) null,
    lugarDestino varchar(100) null,
    marcaVehiculo varchar(50) null,
    motivoDocumento varchar(500) null,
    nombreComercialEmisor varchar(100) null,
    numeroConstanciaVehiculo varchar(100) null,
    numeroDocumentoAdquiriente varchar(15) not null,
    numeroDocumentoRefeAdicional_1 varchar(30) null,
    numeroDocumentoRefeAdicional_2 varchar(30) null,
    numeroDocumentoRefeAdicional_3 varchar(30) null,
    numeroDocumentoRefeAdicional_4 varchar(30) null,
    numeroDocumentoRefeAdicional_5 varchar(30) null,
    numeroDocumentoReferenciaCorre varchar(13) null,
    numeroDocumentoReferenciaPrinc varchar(13) null,
    numeroDocumentoReferencia_1 varchar(30) null,
    numeroDocumentoReferencia_2 varchar(30) null,
    numeroDocumentoReferencia_3 varchar(30) null,
    numeroDocumentoReferencia_4 varchar(30) null,
    numeroDocumentoReferencia_5 varchar(30) null,
    numeroLicenciaConducir varchar(30) null,
    numeroRucTransportista varchar(11) null,
    numeroRucTransportistaCuenta varchar(2) null,
    paisEmisor varchar(2) null,
    paisPtoLlegada varchar(2) null,
    paisPtoPartida varchar(2) null,
    placaVehiculo varchar(10) null,
    porcentajeDetraccion varchar(15) null,
    porcentajePercepcion varchar(15) null,
    porcentajeRetencion varchar(15) null,
    provinciaEmisor varchar(30) null,
    provinciaPtoLlegada varchar(30) null,
    provinciaPtoPartida varchar(30) null,
    razonSocialAdquiriente varchar(100) not null,
    razonSocialEmisor varchar(100) not null,
    razonSocialTransportista varchar(100) null,
    serieNumeroAfectado varchar(13) null,
    serieNumeroDocumentoAnticipo varchar(20) null,
    subTotal varchar(15) null,
    textoAdicionalLeyenda_1 varchar(200) null,
    textoAdicionalLeyenda_10 varchar(200) null,
    textoAdicionalLeyenda_11 varchar(200) null,
    textoAdicionalLeyenda_12 varchar(200) null,
    textoAdicionalLeyenda_13 varchar(200) null,
    textoAdicionalLeyenda_14 varchar(200) null,
    textoAdicionalLeyenda_15 varchar(200) null,
    textoAdicionalLeyenda_16 varchar(200) null,
    textoAdicionalLeyenda_17 varchar(200) null,
    textoAdicionalLeyenda_18 varchar(200) null,
    textoAdicionalLeyenda_19 varchar(200) null,
    textoAdicionalLeyenda_2 varchar(200) null,
    textoAdicionalLeyenda_20 varchar(200) null,
    textoAdicionalLeyenda_3 varchar(200) null,
    textoAdicionalLeyenda_4 varchar(200) null,
    textoAdicionalLeyenda_5 varchar(200) null,
    textoAdicionalLeyenda_6 varchar(200) null,
    textoAdicionalLeyenda_7 varchar(200) null,
    textoAdicionalLeyenda_8 varchar(200) null,
    textoAdicionalLeyenda_9 varchar(200) null,
    textoAuxiliar100_1 varchar(100) null,
    textoAuxiliar100_10 varchar(100) null,
    textoAuxiliar100_2 varchar(100) null,
    textoAuxiliar100_3 varchar(100) null,
    textoAuxiliar100_4 varchar(100) null,
    textoAuxiliar100_5 varchar(100) null,
    textoAuxiliar100_6 varchar(100) null,
    textoAuxiliar100_7 varchar(100) null,
    textoAuxiliar100_8 varchar(100) null,
    textoAuxiliar100_9 varchar(100) null,
    textoAuxiliar250_1 varchar(250) null,
    textoAuxiliar250_10 varchar(250) null,
    textoAuxiliar250_11 varchar(250) null,
    textoAuxiliar250_12 varchar(250) null,
    textoAuxiliar250_13 varchar(250) null,
    textoAuxiliar250_14 varchar(250) null,
    textoAuxiliar250_15 varchar(250) null,
    textoAuxiliar250_16 varchar(250) null,
    textoAuxiliar250_17 varchar(250) null,
    textoAuxiliar250_18 varchar(250) null,
    textoAuxiliar250_19 varchar(250) null,
    textoAuxiliar250_2 varchar(250) null,
    textoAuxiliar250_20 varchar(250) null,
    textoAuxiliar250_21 varchar(250) null,
    textoAuxiliar250_22 varchar(250) null,
    textoAuxiliar250_23 varchar(250) null,
    textoAuxiliar250_24 varchar(250) null,
    textoAuxiliar250_25 varchar(250) null,
    textoAuxiliar250_3 varchar(250) null,
    textoAuxiliar250_4 varchar(250) null,
    textoAuxiliar250_5 varchar(250) null,
    textoAuxiliar250_6 varchar(250) null,
    textoAuxiliar250_7 varchar(250) null,
    textoAuxiliar250_8 varchar(250) null,
    textoAuxiliar250_9 varchar(250) null,
    textoAuxiliar40_1 varchar(40) null,
    textoAuxiliar40_10 varchar(40) null,
    textoAuxiliar40_11 varchar(40) null,
    textoAuxiliar40_12 varchar(40) null,
    textoAuxiliar40_13 varchar(40) null,
    textoAuxiliar40_14 varchar(40) null,
    textoAuxiliar40_15 varchar(40) null,
    textoAuxiliar40_16 varchar(40) null,
    textoAuxiliar40_17 varchar(40) null,
    textoAuxiliar40_18 varchar(40) null,
    textoAuxiliar40_19 varchar(40) null,
    textoAuxiliar40_2 varchar(40) null,
    textoAuxiliar40_20 varchar(40) null,
    textoAuxiliar40_3 varchar(40) null,
    textoAuxiliar40_4 varchar(40) null,
    textoAuxiliar40_5 varchar(40) null,
    textoAuxiliar40_6 varchar(40) null,
    textoAuxiliar40_7 varchar(40) null,
    textoAuxiliar40_8 varchar(40) null,
    textoAuxiliar40_9 varchar(40) null,
    textoAuxiliar500_1 varchar(500) null,
    textoAuxiliar500_2 varchar(500) null,
    textoAuxiliar500_3 varchar(500) null,
    textoAuxiliar500_4 varchar(500) null,
    textoAuxiliar500_5 varchar(500) null,
    textoLeyenda_1 varchar(200) null,
    textoLeyenda_10 varchar(200) null,
    textoLeyenda_11 varchar(200) null,
    textoLeyenda_12 varchar(200) null,
    textoLeyenda_13 varchar(200) null,
    textoLeyenda_14 varchar(200) null,
    textoLeyenda_15 varchar(200) null,
    textoLeyenda_16 varchar(200) null,
    textoLeyenda_17 varchar(200) null,
    textoLeyenda_18 varchar(200) null,
    textoLeyenda_19 varchar(200) null,
    textoLeyenda_2 varchar(200) null,
    textoLeyenda_20 varchar(200) null,
    textoLeyenda_3 varchar(200) null,
    textoLeyenda_4 varchar(200) null,
    textoLeyenda_5 varchar(200) null,
    textoLeyenda_6 varchar(200) null,
    textoLeyenda_7 varchar(200) null,
    textoLeyenda_8 varchar(200) null,
    textoLeyenda_9 varchar(200) null,
    tipoDocumentoAdquiriente varchar(1) not null,
    tipoDocumentoAnticipo varchar(2) null,
    tipoDocumentoReferenciaCorregi varchar(2) null,
    tipoDocumentoReferenciaPrincip varchar(2) null,
    tipoMoneda varchar(3) not null,
    tipoOperacionFactura varchar(2) null,
    tipoReferenciaAdicional_1 varchar(2) null,
    tipoReferenciaAdicional_2 varchar(2) null,
    tipoReferenciaAdicional_3 varchar(2) null,
    tipoReferenciaAdicional_4 varchar(2) null,
    tipoReferenciaAdicional_5 varchar(2) null,
    tipoReferencia_1 varchar(2) null,
    tipoReferencia_2 varchar(2) null,
    tipoReferencia_3 varchar(2) null,
    tipoReferencia_4 varchar(2) null,
    tipoReferencia_5 varchar(2) null,
    totalBonificacion varchar(15) null,
    totalDescuentos varchar(15) null,
    totalDetraccion varchar(15) null,
    totalDocumentoAnticipo varchar(18) null,
    totalFondoInclusionSocial varchar(15) null,
    totalIgv varchar(15) null,
    totalIsc varchar(15) null,
    totalOtrosCargos varchar(15) null,
    totalOtrosTributos varchar(15) null,
    totalPercepcion varchar(15) null,
    totalRetencion varchar(15) null,
    totalValorVentaNetoOpExonerada varchar(15) not null,
    totalValorVentaNetoOpGratuitas varchar(18) null,
    totalValorVentaNetoOpGravadas varchar(15) not null,
    totalValorVentaNetoOpNoGravada varchar(15) not null,
    totalVenta varchar(15) not null,
    totalVentaConPercepcion varchar(15) null,
    ubigeoDireccionPtoLlegada varchar(6) null,
    ubigeoDireccionPtoPartida varchar(6) null,
    ubigeoEmisor varchar(6) null,
    urbanizacion varchar(25) null,
    urbanizacionPtoLlegada varchar(25) null,
    urbanizacionPtoPartida varchar(25) null,
    valorReferencialDetraccion varchar(15) null,
    primary key (numeroDocumentoEmisor, serieNumero, tipoDocumento, tipoDocumentoEmisor)
)
lock datarows;

create table SPE_SUMMARYDETAIL (
    numeroDocumentoEmisor varchar(20) not null,
    numeroFila varchar(5) not null,
    resumenId varchar(17) not null,
    tipoDocumentoEmisor varchar(1) not null,
    numeroCorrelativoFin varchar(8) not null,
    numeroCorrelativoInicio varchar(8) not null,
    serieGrupoDocumento varchar(4) not null,
    tipoDocumento varchar(2) not null,
    tipoMoneda varchar(3) not null,
    totalIgv varchar(15) null,
    totalIsc varchar(15) null,
    totalOtrosCargos varchar(15) null,
    totalOtrosTributos varchar(15) null,
    totalValorVentaOpExoneradasIgv varchar(15) null,
    totalValorVentaOpGratuitas varchar(15) null,
    totalValorVentaOpGravadaConIgv varchar(15) null,
    totalValorVentaOpInafectasIgv varchar(15) null,
    totalVenta varchar(15) null,
    primary key (numeroDocumentoEmisor, numeroFila, resumenId, tipoDocumentoEmisor)
)
lock datarows;

create table SPE_SUMMARYHEADER (
    numeroDocumentoEmisor varchar(20) not null,
    resumenId varchar(17) not null,
    tipoDocumentoEmisor varchar(1) not null,
    bl_cdr image null,
    bl_estadoProceso varchar(40) null,
    bl_estadoRegistro varchar(40) null,
    bl_firma varchar(4000) null,
    bl_hashFirma varchar(4000) null,
    bl_mensaje varchar(4000) null,
    bl_mensajeSunat varchar(4000) null,
    bl_pdf image null,
    bl_urlcdr varchar(4000) null,
    bl_urlpdf varchar(4000) null,
    bl_urlxmlubl varchar(4000) null,
    bl_xml image null,
    bl_xmlubl image null,
    correoEmisor varchar(100) not null,
    fechaEmisionComprobante varchar(10) not null,
    fechaGeneracionResumen varchar(10) not null,
    inHabilitado varchar(1) not null,
    razonSocialEmisor varchar(100) not null,
    resumenTipo varchar(2) not null,
    primary key (numeroDocumentoEmisor, resumenId, tipoDocumentoEmisor)
)
lock datarows;
