<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://ws.ce.ebiz.com/" name="EBizGenericInvoker" targetNamespace="http://ws.ce.ebiz.com/" xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.ce.ebiz.com/" elementFormDefault="unqualified" targetNamespace="http://ws.ce.ebiz.com/" version="1.0">
            <xs:element name="invoke" type="tns:invoke"/>
            <xs:element name="invokeResponse" type="tns:invokeResponse"/>
            <xs:complexType name="invoke">
                <xs:sequence>
                    <xs:element minOccurs="0" name="command" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="invokeResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="invoke">
        <wsdl:part element="ns1:invoke" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="invokeResponse">
        <wsdl:part element="ns1:invokeResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="EBizGenericInvoker">
        <wsdl:operation name="invoke">
            <wsdl:input message="ns1:invoke" name="invoke"></wsdl:input>
            <wsdl:output message="ns1:invokeResponse" name="invokeResponse"></wsdl:output>
        </wsdl:operation>
        <jaxws:bindings>
            <jaxws:enableAsyncMapping>true</jaxws:enableAsyncMapping>
        </jaxws:bindings>
    </wsdl:portType>
</wsdl:definitions>