/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.labtech.einvoice.ws.test;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Arrays;
import java.util.Scanner;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import pe.labtech.einvoice.core.ws.PortInfo;
import pe.labtech.einvoice.core.ws.PortProducer;
import pe.labtech.einvoice.core.ws.generated.EBizGenericInvoker;
import pe.labtech.einvoice.core.ws.generated.EBizGenericInvokerImplService;
import pe.labtech.einvoice.core.ws.generated.InvokeResponse;

/**
 *
 * @author Carlos
 */
public class SubmitFrame extends javax.swing.JFrame {

    /**
     * Creates new form SubmitFrame
     */
    public SubmitFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JScrollPane sourceScroll = new javax.swing.JScrollPane();
        target = new javax.swing.JTextArea();
        javax.swing.JScrollPane targetScroll = new javax.swing.JScrollPane();
        source = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        templates = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane1ComponentResized(evt);
            }
        });

        target.setColumns(20);
        target.setRows(5);
        sourceScroll.setViewportView(target);

        jSplitPane1.setRightComponent(sourceScroll);

        source.setColumns(20);
        source.setRows(5);
        targetScroll.setViewportView(source);

        jSplitPane1.setLeftComponent(targetScroll);

        submit.setText("jButton1");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        templates.setModel(new DefaultComboBoxModel<>());
        templates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(templates, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(templates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double proportion;

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //establecer la posición del componente
        proportion = 0.5d;
        jSplitPane1.setDividerLocation(proportion);

        //mantener la relación de aspecto despues de cambiado el tamaño
        Arrays.stream(jSplitPane1.getComponents())
                .filter(c -> c instanceof BasicSplitPaneDivider)
                .forEach(c -> c.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        proportion = 1d * jSplitPane1.getDividerLocation() / jSplitPane1.getWidth();
//                        System.out.println(proportion);
                    }

                }));

        //escanea y agrega los valores del combo box
        Arrays.stream(new File(".").list())
                .filter(n -> n.startsWith("template"))
                .forEach(n -> ((DefaultComboBoxModel<String>) this.templates.getModel()).addElement(n));

    }//GEN-LAST:event_formWindowOpened

    private void jSplitPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane1ComponentResized
        jSplitPane1.setDividerLocation(proportion);
    }//GEN-LAST:event_jSplitPane1ComponentResized

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //hierarchy construction
        final PortInfo portInfo = new PortInfo();
        portInfo.init();
        final PortProducer pp = new PortProducer(
                new EBizGenericInvokerImplService(),
                portInfo
        );
        pp.init();

        EBizGenericInvoker port = pp.getPort();

        port.invokeAsync(source.getText(), t -> {
            try {
                this.submit.setEnabled(false);
                this.target.setText("");
                InvokeResponse resp = t.get();
                target.setText(resp.getReturn());
            } catch (InterruptedException ex) {
                Logger.getLogger(SubmitFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                //falla del proceso
                StringWriter sw = new StringWriter();
                try (PrintWriter pw = new PrintWriter(sw)) {
                    ex.getCause().printStackTrace(pw);
                }
                target.setText(sw.toString());
            } finally {
                this.submit.setEnabled(true);
            }
        });

    }//GEN-LAST:event_submitActionPerformed

    private void templatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templatesActionPerformed
        try (Scanner scanner = new Scanner(new File((String) this.templates.getSelectedItem()), "UTF-8")) {
            scanner.useDelimiter("\\Z");
            this.source.setText(scanner.next());
        } catch (IOException ex) {
            Logger.getLogger(SubmitFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_templatesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                System.out.println(info.getName());
//                if ("Nimbus".equals(info.getName())) {
//                    break;
//                }
//            }

            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(SubmitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SubmitFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea source;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea target;
    private javax.swing.JComboBox<String> templates;
    // End of variables declaration//GEN-END:variables
}
